version: '3.8'

services:

  nwp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    image: mybuild/nginx-web-proxy
    container_name: nginx-web-proxy
    ports:
      - 8080:80
    env_file:
      - ./.env