version: '3.8'

services:

  build-msf-dependencies:
    build:
      context: .
      dockerfile: Dockerfile.build-msf-dependencies
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    image: mybuild/gvc-alpine-msf-dependencies

  install-metasploit-framework:
    build:
      context: .
      dockerfile: Dockerfile.install-metasploit-framework
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    image: mybuild/gvc-alpine-metasploit
    depends_on:
      - build-msf-dependencies


  build-essentials:
    build:
      context: .
      dockerfile: Dockerfile.build-essentials
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}
    image: mybuild/build-essentials

  test:
      build:
        context: .
        dockerfile: Dockerfile.test
        args:
          KERNEL_VERSION: ${KERNEL_VERSION}
      image: mybuild/test-image      