version: '3.8'

services:

  build-msf-dependencies:
    build:
      context: .
      dockerfile: Dockerfile.build-msf-dependencies
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    image: mybuild/gvc-alpine-msf-dependencies

  install-metasploit-framework:
    build:
      context: .
      dockerfile: Dockerfile.install-metasploit-framework
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    image: mybuild/gvc-alpine-metasploit
    env_file:
      - ./.env
    depends_on:
      - build-msf-dependencies

  build-apk:
    build:
      context: .
      dockerfile: Dockerfile.build-apk
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    image: mybuild/gvc-apk
    volumes:
      - "${PWD}:/data"
    env_file:
      - ./.env
    depends_on:
      - install-metasploit-framework

  sign-apk:
    build:
      context: .
      dockerfile: Dockerfile.sign-apk
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    image: mybuild/gvc-sign-apk
    volumes:
      - "${PWD}:/data"
    env_file:
      - ./.env

  deploy-apk:
    build:
      context: .
      dockerfile: Dockerfile.deploy-apk
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    image: mybuild/my-static-site
    container_name: my-static-site
    ports:
      - "3000:3000"

  build-essentials:
    build:
      context: .
      dockerfile: Dockerfile.build-essentials
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION}
    image: mybuild/build-essentials

  test:
      build:
        context: .
        dockerfile: Dockerfile.test
      image: mybuild/test-image      
      env_file:
      - ./.env