version: '3.8'

services:
  build-essentials:
    build:
      context: .
      dockerfile: Dockerfile.build-essentials
    image: mybuild/build-essentials

  download-kernel-source:
    build:
      context: .
      dockerfile: Dockerfile.download-kernel-source
      args:
        KERNEL_MAJOR_VERSION: ${KERNEL_MAJOR_VERSION}
        KERNEL_VERSION: ${KERNEL_VERSION}
    image: mybuild/download-kernel-source
    depends_on:
      - build-essentials

  compile-kernel:
    build:
      context: .
      dockerfile: Dockerfile.compile-kernel
      args:
        KERNEL_MAJOR_VERSION: ${KERNEL_MAJOR_VERSION}
        KERNEL_VERSION: ${KERNEL_VERSION}

    image: mybuild/compile-kernel
    depends_on:
      - download-kernel-source

  install-kernel:
    build:
      context: .
      dockerfile: Dockerfile
    image: mybuild/install-kernel
    depends_on:
      - compile-kernel