version: '3.9'
services:
  test-berryboot-buildroot-latest:
    build:
      context: .
    volumes:
    - type: volume
      source: buildroot-volume
      target: /buildroot/

volumes:
  buildroot-volume: